file1 = open('anti.txt', 'r', encoding="utf-8")
file2 = open('mashi.txt', 'r', encoding="utf-8")
file3 = open('probeg.txt', 'r', encoding="utf-8")
file4 = open('trans.txt', 'r', encoding="utf-8")
str1 = file1.readline().strip()
str2 = file2.readline().strip()
str4 = file4.readline().strip()
str3 = file3.readline().strip()
print("Сейчас probeg:", str3)
a=int(input("сколько добавить к пробегу?"))
str3=int(str3)
str1=int(str1)
str2=int(str2)
str4=int(str4)
b= str3+a
b=str(b)
file3.close()
file3 = open('probeg.txt', 'w', encoding="utf-8")
str3=int(str3)
str1=int(str1)
str2=int(str2)
str4=int(str4)

file1.close()
file2.close()
file3.close()
file4.close()

file1 = open('anti.txt', 'w', encoding="utf-8")
file2 = open('mashi.txt', 'w', encoding="utf-8")
file3 = open('probeg.txt', 'w', encoding="utf-8")
file4 = open('trans.txt', 'w', encoding="utf-8")

file3.write(b)
file1.write(b)
file2.write(b)
file4.write(b)

file1.close()
file2.close()
file3.close()
file4.close()


