spisok = open("hleb.txt","r", encoding ="utf-8")
str1 = spisok.readline().strip()
print(str1)
str2 = spisok.readline().strip()
print(str2)
str3 = spisok.readline().strip()
print(str3)
str4 = spisok.readline().strip()
print(str4)
spisok.close()
spisok = open("hleb.txt","w", encoding ="utf-8")
spisok.write("--" + str1+ "\n")
spisok.write("--" + str2+ "\n")
spisok.write("--" + str3+ "\n")
spisok.write("--" + str4+ "\n")
spisok.close()
